services:
  redis:
    image: redis:7.2
    container_name: redis-ktb
    restart: unless-stopped
    ports:
      - "${DB_REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:

# DB_REDIS_PORT=6379
